[package]
name = "use_env_logger"
version = "0.1.0"
edition = "2021"
authors = ["kevinxie"]
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
